version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: graphql_poc_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: graphql_user
      POSTGRES_PASSWORD: graphql_pass
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
